Layout/EmptyLines:
  Exclude:
    - 'bin/setup'
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'

Layout/SpaceInsideBrackets:
  Exclude:
    - 'config/environments/production.rb'

Metrics/LineLength:
  Max: 112

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/spring.rb'

Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

Style/StringLiterals:
  Exclude:
    - 'bin/yarn'
    - 'config/application.rb'
    - 'config/environments/production.rb'
    - 'config/puma.rb'
    - 'test/application_system_test_case.rb'

Style/StringLiteralsInInterpolation:
  Exclude:
    - 'bin/yarn'

Style/SymbolArray:
  EnforcedStyle: brackets
